#!/usr/bin/env python3
"""
ML-Based Weather Interpolator (LightGBM) - Optimized
===================================================

Replaces physics-based equations with a Machine Learning approach.
Trains a LightGBM model for EACH timestamp to learn the local weather physics.

OPTIMIZATIONS:
1.  **Static Grid Caching**: Pre-loads and pre-slices the 1.2M pixel grid into RAM/Disk.
2.  **Vectorized Inference**: Feeds raw NumPy arrays to LightGBM (bypassing Pandas overhead).
3.  **Training Data Caching**: Samples point features once and saves to disk.

Performance Target: < 4 minutes total.
"""

import json
import time
import sys
import shutil
from pathlib import Path
from datetime import datetime
import numpy as np
import pandas as pd
import rasterio
from rasterio.transform import xy
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import joblib

# ==============================================================================
# CONFIGURATION
# ==============================================================================

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent

# Input Files
# NOTE: This now uses the NumPy-optimized aggregation (47.6s for 7000 coords vs 16+ min)
WEATHER_JSON = SCRIPT_DIR.parent / "meteo_api/weather_data_3hour.json"  # Generated by aggregate_weather_data.py (NumPy version)
ELEVATION_TIF = SCRIPT_DIR.parent / "terrains/tirol_100m_float.tif"
ASPECT_TIF = SCRIPT_DIR.parent / "terrains/tirol_aspect_100m_web.tif"
SLOPE_TIF = SCRIPT_DIR.parent / "terrains/tirol_slope_100m_float.tif"

# Cache Directory
CACHE_DIR = SCRIPT_DIR / "cache"
CACHE_GRID = CACHE_DIR / "static_grid.joblib"
CACHE_POINTS = CACHE_DIR / "training_points.joblib"

# Output Directory
OUTPUT_BASE = PROJECT_ROOT / "TIFS/100m_resolution_ml"

# Feature Columns (Order matters for NumPy arrays!)
FEATURES = ['elevation', 'aspect', 'slope', 'latitude', 'longitude']

TARGET_VARS = [
    "temperature_2m",
    "relative_humidity_2m",
    "wind_speed_10m",
    "cloud_cover",
    "shortwave_radiation",
    "snowfall",
    "freezing_level_height"
]

# Model Parameters (Optimized for speed)
LGB_PARAMS = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt',
    'num_leaves': 31,
    'learning_rate': 0.1,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': -1,
    'n_jobs': -1,
    'force_col_wise': True # Optimization for large number of columns/rows
}

NUM_ROUNDS = 100

# ==============================================================================
# DATA LOADING & CACHING
# ==============================================================================

def load_static_grid_optimized():
    """
    Loads static terrain, creates valid pixel mask, and returns PRE-SLICED numpy array.
    """
    if CACHE_GRID.exists():
        print("⚡ Loading cached static grid...")
        return joblib.load(CACHE_GRID)

    print("🗺️  Building static grid from TIFs (First Run)...")
    
    with rasterio.open(ELEVATION_TIF) as src:
        elevation = src.read(1)
        profile = src.profile
        height, width = elevation.shape
        transform = src.transform
        
        cols, rows = np.meshgrid(np.arange(width), np.arange(height))
        xs, ys = rasterio.transform.xy(transform, rows, cols)
        
        lon_flat = np.array(xs).flatten()
        lat_flat = np.array(ys).flatten()
        elev_flat = elevation.flatten()
        
    with rasterio.open(ASPECT_TIF) as src:
        aspect_flat = src.read(1).flatten()
        
    with rasterio.open(SLOPE_TIF) as src:
        slope_flat = src.read(1).flatten()
        
    # Create valid mask (ignore NODATA)
    valid_mask = (elev_flat != profile['nodata'])
    
    # Construct the Feature Matrix for Valid Pixels ONLY
    # This keeps memory usage low and inference fast
    X_grid_valid = np.column_stack([
        elev_flat[valid_mask],
        aspect_flat[valid_mask],
        slope_flat[valid_mask],
        lat_flat[valid_mask],
        lon_flat[valid_mask]
    ]).astype(np.float32)
    
    grid_meta = {'shape': (height, width), 'profile': profile}
    
    # Save to cache
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    data = (X_grid_valid, valid_mask, grid_meta)
    joblib.dump(data, CACHE_GRID, compress=3)
    
    print(f"   ✅ Grid Cached: {X_grid_valid.shape[0]} valid pixels")
    return data

def load_training_data_optimized():
    """
    Loads weather data and samples features for points ONCE.
    """
    if CACHE_POINTS.exists():
        print("⚡ Loading cached training points...")
        return joblib.load(CACHE_POINTS)

    print("📊 Processing training data (First Run)...")
    
    with open(WEATHER_JSON, 'r') as f:
        data = json.load(f)
        
    src_elev = rasterio.open(ELEVATION_TIF)
    src_aspect = rasterio.open(ASPECT_TIF)
    src_slope = rasterio.open(SLOPE_TIF)
    
    coord_entries = data.get('coordinates', [])
    point_features = [] # List of [elev, aspect, slope, lat, lon]
    point_weather = []  # List of weather dicts
    
    print(f"   📍 Sampling features for {len(coord_entries)} points...")
    
    for entry in coord_entries:
        info = entry['coordinate_info']
        wdata = entry.get('weather_data_3hour', {}).get('hourly', {})
        
        if not wdata:
            continue
            
        lat = info['latitude']
        lon = info['longitude']
        
        # Sample Rasters
        sample_gen = src_elev.sample([(lon, lat)])
        elev_val = next(sample_gen)[0]
        
        sample_gen = src_aspect.sample([(lon, lat)])
        aspect_val = next(sample_gen)[0]
        
        sample_gen = src_slope.sample([(lon, lat)])
        slope_val = next(sample_gen)[0]
        
        # Append features in correct order
        point_features.append([elev_val, aspect_val, slope_val, lat, lon])
        point_weather.append(wdata)
        
    src_elev.close()
    src_aspect.close()
    src_slope.close()
    
    # Convert features to numpy array for speed
    X_points = np.array(point_features, dtype=np.float32)
    
    data = (X_points, point_weather)
    joblib.dump(data, CACHE_POINTS, compress=3)
    
    print(f"   ✅ Cached {len(point_features)} training points")
    return data

# ==============================================================================
# MAIN PIPELINE
# ==============================================================================

def train_and_predict_fast(target_var, timestamp_idx, X_points, point_weather, X_grid_valid):
    """
    Vectorized training and prediction.
    """
    # 1. Build Target Array (y)
    # We need to filter X_points to match valid y values (some points might lack data)
    y_list = []
    valid_indices = []
    
    for i, wdata in enumerate(point_weather):
        if target_var in wdata:
            val = wdata[target_var][timestamp_idx]
            if val is not None:
                y_list.append(val)
                valid_indices.append(i)
                
    if not y_list:
        return None, 0
        
    y = np.array(y_list, dtype=np.float32)
    X = X_points[valid_indices] # Fancy indexing (fast)
    
    # 2. Train Model
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
    
    train_data = lgb.Dataset(X_train, label=y_train)
    # Silence warnings by setting verbose_eval=False
    bst = lgb.train(
        LGB_PARAMS,
        train_data,
        num_boost_round=NUM_ROUNDS,
        valid_sets=None, # Skip validation during production run for speed? Or keep for stats?
        # callbacks=[lgb.log_evaluation(0)] 
    )
    
    # 3. Predict on Valid Grid Pixels (Vectorized)
    preds = bst.predict(X_grid_valid)
    
    # Quick Validation Score
    y_pred_test = bst.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))
    
    return preds, rmse

def save_tif_fast(data_flat, grid_meta, output_path, valid_mask):
    """Reconstructs image and saves TIF."""
    profile = grid_meta['profile']
    height, width = grid_meta['shape']
    
    # Pre-allocate full array
    full_array = np.full((height * width), profile['nodata'], dtype=np.float32)
    
    # Fill valid pixels
    full_array[valid_mask] = data_flat
    
    # Reshape and Write
    image = full_array.reshape((height, width))
    
    with rasterio.open(output_path, 'w', **profile) as dst:
        dst.write(image, 1)
        # Add metadata tags for traceability
        dst.update_tags(generated_by="xgboost_interpolator", timestamp=datetime.now().isoformat())

def main():
    start_time_global = time.time()
    print("🚀 Starting Optimized ML Interpolation Pipeline")
    print("=" * 50)
    
    # 1. Load Data (Cached)
    X_grid_valid, valid_mask, grid_meta = load_static_grid_optimized()
    X_points, point_weather = load_training_data_optimized()
    
    timestamps = point_weather[0]['time']
    print(f"📅 Found {len(timestamps)} timestamps x {len(TARGET_VARS)} variables")
    
    total_rmse = {var: [] for var in TARGET_VARS}
    
    # Create Base Output Dir
    OUTPUT_BASE.mkdir(parents=True, exist_ok=True)
    
    # 2. Main Loop
    for t_idx, ts in enumerate(timestamps):
        ts_clean = ts.replace(":", "-") # Safe filename
        ts_dir = OUTPUT_BASE / ts
        ts_dir.mkdir(parents=True, exist_ok=True)
        
        # print(f"\n⏰ {ts} ...", end="", flush=True)
        t_start = time.time()
        
        for var in TARGET_VARS:
            preds, rmse = train_and_predict_fast(var, t_idx, X_points, point_weather, X_grid_valid)
            
            if preds is not None:
                out_path = ts_dir / f"{var}.tif"
                save_tif_fast(preds, grid_meta, out_path, valid_mask)
                total_rmse[var].append(rmse)
        
        # Progress bar style output
        elapsed = time.time() - t_start
        print(f"\r✅ [{t_idx+1}/{len(timestamps)}] {ts} completed in {elapsed:.2f}s", end="")
        
    print("\n\n" + "=" * 50)
    print("📊 FINAL ACCURACY REPORT (Average RMSE)")
    print("=" * 50)
    
    for var, scores in total_rmse.items():
        if scores:
            print(f"{var:<25} : {np.mean(scores):.4f}")
            
    print(f"\n✅ Total Execution Time: {time.time() - start_time_global:.1f}s")
    print(f"📁 Output: {OUTPUT_BASE}")

if __name__ == "__main__":
    main()